### ISSUE TITLE
X86 architecture is not supported

### ISSUE THREAD

**Issue by cantops** [cezuni/usbip-win#17]
Will there be any support plan in the future?

**Comment by cantops** [comment]
![qq 20190302174009](https://user-images.githubusercontent.com/178909/53680164-5cf86880-3d12-11e9-991b-511b085bc0b6.png)

**Comment by cezuni** [comment]
@cantops : Currently there's no plan to support x86. 😢 Is your screenshot related to x86 environment ?

**Comment by cantops** [comment]
@cezuni Yes, the driver files compiled with win32 can be installed correctly, but the above error occurred when running usbip！

**Comment by Oxalin** [comment]
0x6f8 means ERROR_INVALID_USER_BUFFER

I'm pretty sure it is caused by a bad type under 32 bit when getting/setting the buffer size. I'll have a look at it in the next few days.

@cezuni sorry for being away these last few weeks, all the family got sick one after the other.

**Comment by Oxalin** [comment]
@cezuni I may be wrong because I'm looking at it on the fly during my lunchtime, but I think the problem comes from using the wrong structure type in usbip-win/userspace/lib/usbip_setupdi.c, at line 115:
pdev_interface_detail->cbSize = sizeof(PSP_DEVICE_INTERFACE_DETAIL_DATA);

I think this should either be (they should be equivalent):
pdev_interface_detail->cbSize = sizeof(SP_DEVICE_INTERFACE_DETAIL_DATA);
or
pdev_interface_detail->cbSize = sizeof(*pdev_interface_detail);

What do you think of it?

**Comment by cezuni** [comment]
@Oxalin : You're correct.

**Comment by Oxalin** [comment]
@cantops Could you test this the referenced build commit? Hopefully, this will fix the error. From there, we should be able to determine if this is working on 32 bit systems or if there is more work to do.

I'll need sometime to install a 32 bit OS in a VM or similar, we could test it regularly from there.

**Comment by cantops** [comment]
@Oxalin okay

**Comment by cantops** [comment]
@Oxalin This build commit is correct and the problem has been solved.
